### ISSUE TITLE
Please keep .certsigningrequest

### ISSUE THREAD

**Issue by programmin1** [fastlane/pem#92]
It appears the pem command doesn't keep the .certsigningrequest when run for an app.

When time comes to renew the push certificate, the easiest way to fix it is to reupload the certsigningrequest, download the new cert and replace wherever you were using the expired one.

**Comment by KrauseFx** [comment]
Sorry, it's currently not planned to keep that file. Any reason why you wouldn't just generate a new PEM file?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1949. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
